spring:
  application:
    name: smp-oauth-service
  profiles:
    active: dev
  config:
    import: nacos:smp-oauth-web-dev.yaml
    enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.22:8848
        namespace: aaa
      config:
        server-addr: 192.168.3.22:8848
        file-extension: yaml
        namespace: aaa
        group: DEFAULT_GROUP

